### ISSUE TITLE
Dimension Stacking Going to nether Crashes.

### ISSUE THREAD

**Issue by Deathjohn** [qouteall/ImmersivePortalsModForForge#100]
I have the dimensions shown as such:
End
Overworld
BeeDimension
Nether
Midnight Dimension
Dimensional Dungeons

With these dropping past the bee dimension into the nether causes a crash. Here is the error report.

The game crashed whilst ticking player
Error: java.lang.NullPointerException: Dimension type must not be null

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 5/13/20 7:53 PM
Description: Ticking player

java.lang.NullPointerException: Dimension type must not be null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225) ~[commons-lang3-3.5.jar:3.5] {}
	at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:182) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:MixinForgeDimensionManager,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:1004) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:altius_world.MixinMinecraftServer_A,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinMinecraftServer,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:MixinMinecraftServer_MA,pl:mixin:A}
	at net.telepathicgrunt.bumblezone.entities.PlayerTeleportationBehavior.teleportByOutOfBounds(PlayerTeleportationBehavior.java:264) ~[?:?] {re:classloading}
	at net.telepathicgrunt.bumblezone.entities.PlayerTeleportationBehavior.access$300(PlayerTeleportationBehavior.java:45) ~[?:?] {re:classloading}
	at net.telepathicgrunt.bumblezone.entities.PlayerTeleportationBehavior$ForgeEvents.playerTick(PlayerTeleportationBehavior.java:184) ~[?:?] {re:classloading,pl:eventbus:A}
	at net.minecraftforge.eventbus.ASMEventHandler_60_ForgeEvents_playerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:84) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:206) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:alternate_dimension.MixinPlayerEntity_A,pl:mixin:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:361) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:entity_sync.MixinServerPlayerEntity,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:MixinServerPlayerEntity_MA,pl:mixin:A}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:alternate_dimension.MixinServerPlayNetworkHandler_A,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:position_sync.MixinServerPlayNetworkHandler,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:alternate_dimension/MixinServerPlayNetworkHandler_A,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:block_manipulation/MixinServerPlayNetworkHandler_B,pl:mixin:A}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:MixinClientConnection,pl:mixin:A}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:altius_world.MixinMinecraftServer_A,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinMinecraftServer,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:MixinMinecraftServer_MA,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:altius_world.MixinMinecraftServer_A,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinMinecraftServer,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:MixinMinecraftServer_MA,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:163) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:altius_world.MixinMinecraftServer_A,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinMinecraftServer,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:MixinMinecraftServer_MA,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
	at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:182)
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:1004)
	at net.telepathicgrunt.bumblezone.entities.PlayerTeleportationBehavior.teleportByOutOfBounds(PlayerTeleportationBehavior.java:264)
	at net.telepathicgrunt.bumblezone.entities.PlayerTeleportationBehavior.access$300(PlayerTeleportationBehavior.java:45)
	at net.telepathicgrunt.bumblezone.entities.PlayerTeleportationBehavior$ForgeEvents.playerTick(PlayerTeleportationBehavior.java:184)
	at net.minecraftforge.eventbus.ASMEventHandler_60_ForgeEvents_playerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:84)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:206)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 231
	Entity Name: Deathjohn_
	Entity's Exact location: 151.32, -1.08, 307.57
	Entity's Block location: World: (151,-2,307), Chunk: (at 7,-1,3 in 9,19; contains blocks 144,0,304 to 159,255,319), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:361)
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@30d07ba
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:163)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4384108040 bytes (4181 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.87.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.87.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.87.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.87.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre16.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.1.87.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/OptiForge-MC1.15.2-0.1.17.jar optiforge TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.87
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.87-client.jar Minecraft {minecraft@1.15.2 DONE}
		repurposedstructures-1.15.2-1.4.1.jar Repurposed Structures {repurposed_structures@1.15.2-1.4.1 DONE}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 DONE}
		SlimyBoyos-2.0.1.jar SlimyBoyos {slimyboyos@2.0.1 DONE}
		BiomesOPlenty-1.15.2-10.0.0.358-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.358 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		OptiForge-MC1.15.2-0.1.17.jar OptiForge {optiforge@0.1.17 DONE}
		mcw-windows-1.0.1-mc1.15.2_1.15.1.jar Macaw's Windows {mcwwindows@1.0.1 DONE}
		Upgrade-Aquatic-1.15.2-v1.5.1.jar Upgrade Aquatic {upgrade_aquatic@1.5.1 DONE}
		dimdungeons-1.051-forge-1.15.2.jar Dimensional Dungeons {dimdungeons@1.15.2-1.05 DONE}
		BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 DONE}
		TerraForged-1.15.2-0.0.14.jar TerraForged {terraforged@0.0.14 DONE}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 DONE}
		comforts-FORGE-1.15.2-2.0.0.2.jar Comforts {comforts@FORGE-1.15.2-2.0.0.2 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		DoubleSlabs-1.15-2.2.7.jar Double Slabs {doubleslabs@2.2.7 DONE}
		themidnight-0.5.7-3.jar The Midnight {midnight@0.5.7-3 DONE}
		lostcities-1.15-3.0.1-alpha.jar LostCities {lostcities@1.15-3.0.1-alpha DONE}
		BasicNetherOres-1.15.2-4.0.1.jar Basic Nether Ores {bno@4.0.1 DONE}
		The-Endergetic-Expansion-1.15.2-v1.2.8.jar The Endergetic Expansion {endergetic@1.2.8 DONE}
		SnowRealMagic-1.15.2-1.7.5.jar Snow! Real Magic! {snowrealmagic@1.7.5 DONE}
		Kiwi-1.15.2-2.6.5.jar Kiwi {kiwi@2.6.5 DONE}
		the_bumblezone-1.15.2-1.2.0.jar The Bumblezone {the_bumblezone@1.15.2-1.2.0 DONE}
		immersive-portals-0.18(forMc1.15withForge).jar Immersive Portals {immersive_portals@0.18 DONE}
		forge-1.15.2-31.1.87-universal.jar Forge {forge@31.1.87 DONE}
		Quark-r2.1-236.jar Quark {quark@r2.1-236 DONE}
		Aquaculture-1.15.2-2.0.13.jar Aquaculture 2 {aquaculture@1.15.2-2.0.13 DONE}
		More+Dogs+1.15.2-1.0.5.jar More Dog Breeds {moredogs@1.0.4 DONE}
	Kiwi Modules: 
		kiwi:contributors
		snowrealmagic:snowrealmagic
	Player Count: 1 / 8; [ServerPlayerEntity['Deathjohn_'/231, l='WTF', x=151.32, y=-1.08, z=307.57]]
	Data Packs: mod:optiforge, vanilla, mod:repurposed_structures, mod:swingthroughgrass (incompatible), mod:slimyboyos (incompatible), mod:biomesoplenty, mod:jei (incompatible), mod:mcwwindows, mod:upgrade_aquatic (incompatible), mod:dimdungeons, mod:bettercaves (incompatible), mod:terraforged, mod:clumps (incompatible), mod:comforts (incompatible), mod:autoreglib (incompatible), mod:doubleslabs, mod:midnight, mod:lostcities (incompatible), mod:bno (incompatible), mod:endergetic (incompatible), mod:snowrealmagic, mod:kiwi, mod:the_bumblezone, mod:immersive_portals (incompatible), mod:forge (incompatible), mod:quark, mod:aquaculture, mod:moredogs
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre16
	OptiFine Build: 20200506-004910
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 445.87
	OpenGlRenderer: GeForce RTX 2060 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by Deathjohn** [comment]
I found the problem is with the bee dimension mod. Its null for some reason.
https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge

**Comment by qouteall** [comment]
Bumblezone has a feature that if the player goes beyond 0 or 256 in overworld then it will teleport to the bee dimension. It's being null may be some dimension registering problem

**Comment by Deathjohn** [comment]
I saw that in the crash log but wasnt too sure. I'll have to contact the mod owner of bumblezone to see if he could fix that.
