### ISSUE TITLE
Crash on load with Optiforge and Optifine MC 1.14.4

### ISSUE THREAD

**Issue by 1337god** [qouteall/ImmersivePortalsModForForge#108]
Optifine version: OptiFine 1.14.4 HD U F5
Optiforge version: OptiForge 0.1.1

```
[19May2020 01:04:10.917] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, fmlclient, --fml.forgeVersion, 28.2.16, --fml.mcVersion, 1.14.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20190829.143755, --username, DaisukeJigen, --version, 1.14.4-forge-28.2.16, --gameDir, /home/lain/.technic/modpacks/hycraft-tales, --assetsDir, /home/lain/.technic/assets, --assetIndex, 1.14, --uuid, cb1791bae15148b3bcf085197092acae, --accessToken, ❄❄❄❄❄❄❄❄, --userType, mojang, --versionType, release, --title, Hycraft Tales, --icon, /home/lain/.technic/assets/packs/hycraft-tales/icon.png]
[19May2020 01:04:10.922] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 4.1.0+62+5bfa59b starting: java version 1.8.0_201 by Oracle Corporation
[19May2020 01:04:11.087] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[19May2020 01:04:11.089] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFine ZIP file: /home/lain/.technic/modpacks/hycraft-tales/mods/OptiFine_1.14.4_HD_U_F5.jar
[19May2020 01:04:11.266] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[19May2020 01:04:11.308] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[19May2020 01:04:11.710] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/home/lain/.technic/modpacks/hycraft-tales/mods/MixinBootstrap-1.0.3.jar Service=ModLauncher Env=CLIENT
[19May2020 01:04:13.422] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[19May2020 01:04:13.446] [main/INFO] [optifine.OptiFineTransformer/]: Targets: 244
[19May2020 01:04:15.986] [main/INFO] [optifine.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
[19May2020 01:04:16.185] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [mods.betterfoliage.MixinConnector]
[19May2020 01:04:16.193] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.qouteall.immersive_portals.MyMixinConnector]
[19May2020 01:04:16.201] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [io.github.zekerzhayard.optiforge.asm.MixinConnector]
[19May2020 01:04:16.259] [main/INFO] [Portal/]: Invoking Mixin Connector
[19May2020 01:04:16.268] [main/ERROR] [mixin/]: Mixin config assets/immersive_portals/immersive_portals.mixins.json does not specify "minVersion" property
[19May2020 01:04:16.280] [main/ERROR] [mixin/]: Mixin config assets/immersive_portals/immersive_portals.mixins_client.json does not specify "minVersion" property
[19May2020 01:04:16.621] [main/ERROR] [mixin/]: Mixin config assets/immersive_portals/immersive_portals.mixins_with_optifine.json does not specify "minVersion" property
[19May2020 01:04:16.624] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.14.4-forge-28.2.16, --gameDir, /home/lain/.technic/modpacks/hycraft-tales, --assetsDir, /home/lain/.technic/assets, --uuid, cb1791bae15148b3bcf085197092acae, --username, DaisukeJigen, --assetIndex, 1.14, --accessToken, ❄❄❄❄❄❄❄❄, --userType, mojang, --versionType, release, --title, Hycraft Tales, --icon, /home/lain/.technic/assets/packs/hycraft-tales/icon.png]
[19May2020 01:04:16.662] [main/INFO] [OptiForge/]:  - Add a transformer: io.github.zekerzhayard.optiforge.asm.transformers.net.minecraft.client.renderer.entity.ItemFrameRendererTransformer
[19May2020 01:04:16.662] [main/INFO] [OptiForge/]: Add 1 transformer(s) totally.
[19May2020 01:04:16.888] [main/INFO] [net.minecraftforge.coremod.CoreMod.environs/COREMODLOG]: [blockstate.js] Added block effect cache field
[19May2020 01:04:16.892] [main/INFO] [net.minecraftforge.coremod.CoreMod.mobeffects/COREMODLOG]: [blockstate.js] Added hasfootprint cache field
[19May2020 01:04:16.894] [main/INFO] [net.minecraftforge.coremod.CoreMod.mobeffects/COREMODLOG]: [blockstate.js] Added acoustic cache field
[19May2020 01:04:16.992] [main/INFO] [net.minecraftforge.coremod.CoreMod.sndctrl/COREMODLOG]: [clientworld.js] Hooked ClientWorld.invalidateRegionAndSetBlock()
[19May2020 01:04:20.824] [main/WARN] [mixin/]: @Mixin target net/minecraft/client/renderer/WorldRenderer$LocalRenderInformationContainer is public in assets/immersive_portals/immersive_portals.mixins_client.json:MixinWorldRendererChunkInfo and should be specified in value
[19May2020 01:04:21.656] [main/INFO] [STDOUT/]: [net.minecraft.client.main.Main:main:76]: Completely ignored arguments: [--title, Hycraft Tales, --icon, /home/lain/.technic/assets/packs/hycraft-tales/icon.png]
[19May2020 01:04:21.893] [Client thread/INFO] [net.minecraftforge.coremod.CoreMod.sndctrl/COREMODLOG]: [clientworld.js] Hooked ClientWorld.invalidateRegionAndSetBlock()
[19May2020 01:04:21.915] [Client thread/WARN] [mixin/]: Re-entrance detected, this will cause serious problems.
org.spongepowered.asm.mixin.transformer.throwables.ReEntrantTransformerError: Re-entrance error.
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:336) ~[MixinBootstrap-1.0.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:206) ~[MixinBootstrap-1.0.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:109) ~[MixinBootstrap-1.0.3.jar:?]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:135) ~[MixinBootstrap-1.0.3.jar:?]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:80) ~[modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115) ~[modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:241) ~[modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:128) ~[modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-4.1.0.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:20) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClass(ModLauncherService.java:19) ~[eventbus-1.0.0-service.jar:1.0.0+54+3f83a9e]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClass(ILaunchPluginService.java:102) ~[modlauncher-4.1.0.jar:4.1.0+62+5bfa59b]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:80) ~[modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115) ~[modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:241) ~[modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.buildTransformedClassNodeFor(TransformingClassLoader.java:133) ~[modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$null$9(LaunchPluginHandler.java:90) ~[modlauncher-4.1.0.jar:?]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.getClassNode(MixinLaunchPlugin.java:212) ~[MixinBootstrap-1.0.3.jar:?]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.getClassNode(MixinLaunchPlugin.java:200) ~[MixinBootstrap-1.0.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1843) ~[MixinBootstrap-1.0.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forType(ClassInfo.java:1897) ~[MixinBootstrap-1.0.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forDescriptor(ClassInfo.java:1876) ~[MixinBootstrap-1.0.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:739) ~[MixinBootstrap-1.0.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:726) ~[MixinBootstrap-1.0.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:297) ~[MixinBootstrap-1.0.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:267) ~[MixinBootstrap-1.0.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1271) ~[MixinBootstrap-1.0.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[MixinBootstrap-1.0.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[MixinBootstrap-1.0.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570) ~[MixinBootstrap-1.0.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[MixinBootstrap-1.0.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:206) ~[MixinBootstrap-1.0.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:109) ~[MixinBootstrap-1.0.3.jar:?]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:135) ~[MixinBootstrap-1.0.3.jar:?]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:80) ~[modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115) ~[modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:241) ~[modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:128) ~[modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-4.1.0.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
	at net.minecraft.client.main.Main.main(SourceFile:155) ~[minecraft.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.14.4-28.2.16-launcher.jar:28.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:42) [ForgeWrapper-1.4.1.jar:?]
[19May2020 01:04:22.017] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[19May2020 01:04:22.017] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[19May2020 01:04:22.017] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[19May2020 01:04:22.017] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[19May2020 01:04:22.017] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
[19May2020 01:04:22.017] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[19May2020 01:04:22.017] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:42)
[19May2020 01:04:22.018] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[19May2020 01:04:22.018] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19May2020 01:04:22.018] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19May2020 01:04:22.018] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19May2020 01:04:22.018] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19May2020 01:04:22.018] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
[19May2020 01:04:22.018] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[19May2020 01:04:22.018] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 5 more
[19May2020 01:04:22.018] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.ReEntrantTransformerError: Re-entrance error.
[19May2020 01:04:22.018] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:336)
[19May2020 01:04:22.018] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:206)
[19May2020 01:04:22.018] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:109)
[19May2020 01:04:22.019] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:135)
[19May2020 01:04:22.019] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:80)
[19May2020 01:04:22.019] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115)
[19May2020 01:04:22.019] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:241)
[19May2020 01:04:22.019] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:128)
[19May2020 01:04:22.019] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[19May2020 01:04:22.019] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19May2020 01:04:22.019] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62)
[19May2020 01:04:22.019] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44)
[19May2020 01:04:22.019] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:20)
[19May2020 01:04:22.019] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraftforge.eventbus.service.ModLauncherService.processClass(ModLauncherService.java:19)
[19May2020 01:04:22.019] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClass(ILaunchPluginService.java:102)
[19May2020 01:04:22.019] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:80)
[19May2020 01:04:22.019] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115)
[19May2020 01:04:22.020] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:241)
[19May2020 01:04:22.020] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader.buildTransformedClassNodeFor(TransformingClassLoader.java:133)
[19May2020 01:04:22.020] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$null$9(LaunchPluginHandler.java:90)
[19May2020 01:04:22.020] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.getClassNode(MixinLaunchPlugin.java:212)
[19May2020 01:04:22.020] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.getClassNode(MixinLaunchPlugin.java:200)
[19May2020 01:04:22.020] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1843)
[19May2020 01:04:22.020] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.ClassInfo.forType(ClassInfo.java:1897)
[19May2020 01:04:22.020] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.ClassInfo.forDescriptor(ClassInfo.java:1876)
[19May2020 01:04:22.020] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:739)
[19May2020 01:04:22.020] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:726)
[19May2020 01:04:22.020] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:297)
[19May2020 01:04:22.020] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:267)
[19May2020 01:04:22.020] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1271)
[19May2020 01:04:22.021] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
[19May2020 01:04:22.021] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[19May2020 01:04:22.021] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
[19May2020 01:04:22.021] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[19May2020 01:04:22.021] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:206)
[19May2020 01:04:22.021] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:109)
[19May2020 01:04:22.021] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:135)
[19May2020 01:04:22.021] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:80)
[19May2020 01:04:22.021] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115)
[19May2020 01:04:22.021] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:241)
[19May2020 01:04:22.021] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:128)
[19May2020 01:04:22.021] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[19May2020 01:04:22.021] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19May2020 01:04:22.021] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[19May2020 01:04:22.022] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	... 11 more
```

**Comment by LoganDark** [comment]
It would be more helpful if you uploaded the file instead of pasting the crash in one line.

**Comment by 1337god** [comment]
> It would be more helpful if you uploaded the file instead of pasting the crash in one line.

That's the whole log file tho

**Comment by LoganDark** [comment]
> That's the whole log file tho

I can't read it because you dumped it all into one line. Please upload the crash report as a text file, or use \`\`\` (three backticks) to properly format it as a code block.

**Comment by 1337god** [comment]
[2020-05-19-1.log](https://github.com/qouteall/ImmersivePortalsModForForge/files/4647506/2020-05-19-1.log)
[debug-1.log](https://github.com/qouteall/ImmersivePortalsModForForge/files/4647509/debug-1.log)

**Comment by LoganDark** [comment]
unfortunately 1.14 is no longer supported, please upgrade. We are no longer able to resolve any incompatibilities with other mods

**Comment by 1337god** [comment]
> unfortunately 1.14 is no longer supported, please upgrade. We are no longer able to resolve any incompatibilities with other mods

Sad, but well I guess I gotta remove Optiforge.

**Comment by LoganDark** [comment]
> I guess I gotta remove Optiforge.

Not sure if that is the issue, but are you sure you need optiforge for 1.14?

**Comment by 1337god** [comment]
> > I guess I gotta remove Optiforge.
> 
> Not sure if that is the issue, but are you sure you need optiforge for 1.14?

Without it it doesn't seem to load :/

**Comment by qouteall** [comment]
Using older forge (28.1.114) can fix it.
