### ISSUE TITLE
Game crash with portal global to normal conversion command in forge 35.1.13 with immersive portal 0.11 (1.16.4)

### ISSUE THREAD

**Issue by solarblindfull** [qouteall/ImmersivePortalsModForForge#187]
Hello ! It's me again !

My test on your lastest mod version concluded on a crash when I typed the command below : 

"/portal global convert_global_portal_to_normal" after a global portal creation with the nether as destination

Here the crash log : 

<details>
  <summary>Click_on_me_please!</summary>
  
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 21/12/20 23:48
Description: Ticking entity

java.lang.IllegalArgumentException: too big
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158) ~[commons-lang3-3.5.jar:3.5] {}
	at com.qouteall.immersive_portals.McHelper.foreachEntities(McHelper.java:505) ~[?:0.11] {re:mixin,re:classloading}
	at com.qouteall.immersive_portals.McHelper.foreachEntitiesByBoxApproximateRegions(McHelper.java:587) ~[?:0.11] {re:mixin,re:classloading}
	at com.qouteall.immersive_portals.McHelper.foreachEntitiesByBox(McHelper.java:570) ~[?:0.11] {re:mixin,re:classloading}
	at com.qouteall.immersive_portals.McHelper.findEntitiesByBox(McHelper.java:561) ~[?:0.11] {re:mixin,re:classloading}
	at com.qouteall.immersive_portals.render.PortalRenderInfo.updateGrouping(PortalRenderInfo.java:286) ~[?:0.11] {re:classloading,pl:runtimedistcleaner:A}
	at com.qouteall.immersive_portals.render.PortalRenderInfo.tick(PortalRenderInfo.java:136) ~[?:0.11] {re:classloading,pl:runtimedistcleaner:A}
	at com.qouteall.immersive_portals.render.PortalRenderInfo.lambda$init$0(PortalRenderInfo.java:89) ~[?:0.11] {re:classloading,pl:runtimedistcleaner:A}
	at com.qouteall.immersive_portals.render.PortalRenderInfo$$Lambda$9340/582442390.accept(Unknown Source) ~[?:?] {}
	at com.qouteall.immersive_portals.my_util.SignalArged.lambda$emit$0(SignalArged.java:18) ~[?:0.11] {re:classloading}
	at com.qouteall.immersive_portals.my_util.SignalArged$$Lambda$13638/700702276.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {re:computing_frames}
	at com.qouteall.immersive_portals.my_util.SignalArged.emit(SignalArged.java:18) ~[?:0.11] {re:classloading}
	at com.qouteall.immersive_portals.portal.Portal.func_70071_h_(Portal.java:394) ~[?:0.11] {re:mixin,re:classloading}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld$$Lambda$13056/977092145.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:common.MixinWorld,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1483) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.13.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$490/1451516720.call(Unknown Source) [forge-1.16.4-35.1.13.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158) ~[commons-lang3-3.5.jar:3.5] {}
	at com.qouteall.immersive_portals.McHelper.foreachEntities(McHelper.java:505) ~[?:0.11] {re:mixin,re:classloading}
	at com.qouteall.immersive_portals.McHelper.foreachEntitiesByBoxApproximateRegions(McHelper.java:587) ~[?:0.11] {re:mixin,re:classloading}
	at com.qouteall.immersive_portals.McHelper.foreachEntitiesByBox(McHelper.java:570) ~[?:0.11] {re:mixin,re:classloading}
	at com.qouteall.immersive_portals.McHelper.findEntitiesByBox(McHelper.java:561) ~[?:0.11] {re:mixin,re:classloading}
	at com.qouteall.immersive_portals.render.PortalRenderInfo.updateGrouping(PortalRenderInfo.java:286) ~[?:0.11] {re:classloading,pl:runtimedistcleaner:A}
	at com.qouteall.immersive_portals.render.PortalRenderInfo.tick(PortalRenderInfo.java:136) ~[?:0.11] {re:classloading,pl:runtimedistcleaner:A}
	at com.qouteall.immersive_portals.render.PortalRenderInfo.lambda$init$0(PortalRenderInfo.java:89) ~[?:0.11] {re:classloading,pl:runtimedistcleaner:A}
	at com.qouteall.immersive_portals.render.PortalRenderInfo$$Lambda$9340/582442390.accept(Unknown Source) ~[?:?] {}
	at com.qouteall.immersive_portals.my_util.SignalArged.lambda$emit$0(SignalArged.java:18) ~[?:0.11] {re:classloading}
	at com.qouteall.immersive_portals.my_util.SignalArged$$Lambda$13638/700702276.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {re:computing_frames}
	at com.qouteall.immersive_portals.my_util.SignalArged.emit(SignalArged.java:18) ~[?:0.11] {re:classloading}
	at com.qouteall.immersive_portals.portal.Portal.func_70071_h_(Portal.java:394) ~[?:0.11] {re:mixin,re:classloading}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld$$Lambda$13056/977092145.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: immersive_portals:end_floor_portal (com.qouteall.immersive_portals.portal.global_portals.VerticalConnectingPortal)
	Entity ID: 17203
	Entity Name: entity.immersive_portals.end_floor_portal
	Entity's Exact location: 0.00, 0.00, 0.00
	Entity's Block location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:common.MixinWorld,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:A}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['player'/2764, l='ClientWorld undergarden:undergarden', x=0.50, y=0.20, z=0.50]]
	Chunk stats: Client Chunks (ImmPtl) 1225
	Level dimension: undergarden:undergarden
	Level spawn location: World: (192,63,-160), Chunk: (at 0,3,0 in 12,-10; contains blocks 192,0,-160 to 207,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 7436 game time, 3771 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.13.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$490/1451516720.call(Unknown Source) [forge-1.16.4-35.1.13.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}

</details>

Can you see what's wrong please ?

Thank you very much ! Have a good day !

**Comment by qouteall** [comment]
Fixed. Will be in the next version.

**Comment by solarblindfull** [comment]
Thank you very much for this quick fix !
