### ISSUE TITLE
Lag Spikes

### ISSUE THREAD

**Issue by ghost** [qouteall/ImmersivePortalsModForForge#197]
1.16.4
immersive-portals-0.11-mc1.16.4-forge.jar
[11Jan2021 01:10:05.911] [Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
java.lang.IllegalStateException: handling packet in ResourceKey[minecraft:dimension / minecraft:overworld]
	at com.qouteall.immersive_portals.network.CommonNetworkClient.lambda$doProcessRedirectedMessage$3(CommonNetworkClient.java:77) ~[?:0.11]
	at com.qouteall.immersive_portals.network.CommonNetworkClient$$Lambda$40919/322049082.get(Unknown Source) ~[?:?]
	at com.qouteall.immersive_portals.my_util.LimitedLogger.lambda$throwException$2(LimitedLogger.java:33) ~[?:0.11]
	at com.qouteall.immersive_portals.my_util.LimitedLogger$$Lambda$40920/634472349.run(Unknown Source) ~[?:?]

**Comment by qouteall** [comment]
1. Use the latest version
2. Does the issue happen with only IP?
3. Show the full log

**Comment by ghost** [comment]
Updating to latest version and will let you know w/ full log if happens again thanks

**Comment by ghost** [comment]
Well it seems that this mod was not the source (potentially a contributor) of the lag spikes as having it removed or not does not prevent the spikes, but does prevent that error

**Comment by ghost** [comment]
Using latest version and this is spamming the debug log still - not sure that it's causing any issues though -

```Caused by: java.lang.NullPointerException
[13Jan2021 00:08:08.721] [Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
java.lang.IllegalStateException: handling packet in ResourceKey[minecraft:dimension / minecraft:overworld]
	at com.qouteall.immersive_portals.network.CommonNetworkClient.lambda$doProcessRedirectedMessage$3(CommonNetworkClient.java:77) ~[?:0.12]
	at com.qouteall.immersive_portals.network.CommonNetworkClient$$Lambda$40140/1969828789.get(Unknown Source) ~[?:?]
	at com.qouteall.immersive_portals.my_util.LimitedLogger.lambda$throwException$2(LimitedLogger.java:33) ~[?:0.12]
	at com.qouteall.immersive_portals.my_util.LimitedLogger$$Lambda$40141/273087193.run(Unknown Source) ~[?:?]
	at com.qouteall.immersive_portals.my_util.LimitedLogger.invoke(LimitedLogger.java:27) ~[?:0.12]
	at com.qouteall.immersive_portals.my_util.LimitedLogger.throwException(LimitedLogger.java:32) ~[?:0.12]
	at com.qouteall.immersive_portals.network.CommonNetworkClient.doProcessRedirectedMessage(CommonNetworkClient.java:76) ~[?:0.12]
	at com.qouteall.immersive_portals.network.CommonNetworkClient.lambda$processRedirectedPacket$0(CommonNetworkClient.java:42) ~[?:0.12]
	at com.qouteall.immersive_portals.network.CommonNetworkClient$$Lambda$38704/1435607109.run(Unknown Source) ~[?:?]
	at com.qouteall.immersive_portals.CHelper.executeOnRenderThread(CHelper.java:262) ~[?:0.12]
	at com.qouteall.immersive_portals.network.CommonNetworkClient.processRedirectedPacket(CommonNetworkClient.java:49) ~[?:0.12]
	at com.qouteall.hiding_in_the_bushes.network.StcRedirected.doProcessRedirectedPacket(StcRedirected.java:55) ~[?:0.12]
	at com.qouteall.hiding_in_the_bushes.network.StcRedirected.lambda$handle$0(StcRedirected.java:77) ~[?:0.12]
	at com.qouteall.hiding_in_the_bushes.network.StcRedirected$$Lambda$38703/642830033.run(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?]
	at com.qouteall.hiding_in_the_bushes.network.StcRedirected.handle(StcRedirected.java:77) ~[?:0.12]
	at com.qouteall.hiding_in_the_bushes.network.NetworkMain$$Lambda$30353/1000103904.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$37769/1902861682.accept(Unknown Source) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2988/1852600891.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2990/1246134024.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:88) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$37757/1780245902.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:88) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$38187/1282873077.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:172) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:134) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.36.jar:35.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$491/697796273.call(Unknown Source) [forge-1.16.4-35.1.36.jar:35.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]```

**Comment by qouteall** [comment]
Show the full log

**Comment by ghost** [comment]
sorry I no longer have the mod installed or the debug file
