### ISSUE TITLE
World Crash when Loading RFTools Dimension due to Conflict With Immersive Portals

### ISSUE THREAD

**Issue by Phyronian** [qouteall/ImmersivePortalsModForForge#223]
I'm running a modpack with both RFTools Dimensions and Immersive Portals mods, and when I first load a new RFTools dimension the game crashes to the launcher.  This is the error message generated from the crash:

> [02Mar2021 11:56:23.132] [Server thread/INFO] [Portal/]: Chunk Tracking Graph Force Remove AirStarting
[02Mar2021 11:56:23.145] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Start teleportation...
[02Mar2021 11:56:23.187] [Render thread/WARN] [net.minecraft.world.World/]: Entity EntityCrow['Crow'/214, l='ClientWorld minecraft:overworld', x=319.63, y=64.02, z=-147.82] left loaded chunk area
[02Mar2021 11:56:23.391] [Server thread/INFO] [net.minecraft.server.integrated.IntegratedServer/]: Saving and pausing game...
[02Mar2021 11:56:23.398] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerWorld minecraft:overworld New World'/minecraft:overworld
[02Mar2021 11:56:23.412] [Render thread/INFO] [Portal/]: WorldRenderer reloaded rftoolsdim:diamond
[02Mar2021 11:56:23.454] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Whoosh!
[02Mar2021 11:56:24.133] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerWorld minecraft:the_nether New World'/minecraft:the_nether
[02Mar2021 11:56:24.133] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerWorld minecraft:the_end New World'/minecraft:the_end
[02Mar2021 11:56:24.134] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerWorld rftoolsdim:test New World'/rftoolsdim:test
[02Mar2021 11:56:24.134] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerWorld luminium:void_dimension New World'/luminium:void_dimension
[02Mar2021 11:56:24.135] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerWorld appliedenergistics2:spatial_storage New World'/appliedenergistics2:spatial_storage
[02Mar2021 11:56:24.135] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerWorld rftoolsdim:deru New World'/rftoolsdim:deru
[02Mar2021 11:56:24.135] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerWorld immersive_portals:alternate1 New World'/immersive_portals:alternate1
[02Mar2021 11:56:24.136] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerWorld immersive_portals:alternate2 New World'/immersive_portals:alternate2
[02Mar2021 11:56:24.136] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerWorld immersive_portals:alternate3 New World'/immersive_portals:alternate3
[02Mar2021 11:56:24.137] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerWorld immersive_portals:alternate4 New World'/immersive_portals:alternate4
[02Mar2021 11:56:24.137] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerWorld immersive_portals:alternate5 New World'/immersive_portals:alternate5
[02Mar2021 11:56:24.138] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerWorld rftoolsdim:daaaa New World'/rftoolsdim:daaaa
[02Mar2021 11:56:24.138] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerWorld rftoolsdim:diamond New World'/rftoolsdim:diamond
[02Mar2021 11:56:24.201] [Render thread/INFO] [Portal/]: WorldRenderer reloaded minecraft:overworld
[02Mar2021 11:56:24.210] [Render thread/INFO] [Portal/]: Client World Created minecraft:overworld
[02Mar2021 11:56:24.284] [Server thread/INFO] [Portal/]: ignored dubious move packet rftoolsdim:diamond 382.59620693950086 70.0 -134.26113159015347 8.5 66.5 8.5
[02Mar2021 11:56:24.354] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.RuntimeException: Missing Dimension ResourceKey[minecraft:dimension / rftoolsdim:diamond]
	at com.qouteall.immersive_portals.dimension_sync.DimensionIdRecord.getIntId(DimensionIdRecord.java:39) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.immersive_portals.dimension_sync.DimId.writeWorldId(DimId.java:24) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.hiding_in_the_bushes.network.StcRedirected.encode(StcRedirected.java:59) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.hiding_in_the_bushes.network.NetworkMain$$Lambda$14046/1916949763.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryEncode$4(IndexedMessageCodec.java:134) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$17643/1620426055.accept(Unknown Source) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryEncode(IndexedMessageCodec.java:132) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.build(IndexedMessageCodec.java:147) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.encodeMessage(SimpleChannel.java:85) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.toBuffer(SimpleChannel.java:98) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.toVanillaPacket(SimpleChannel.java:129) ~[?:?]
	at com.qouteall.hiding_in_the_bushes.MyNetwork.createRedirectedMessage(MyNetwork.java:47) ~[?:0.16-mc1.16.5-forge]
	at net.minecraft.server.management.PlayerList.handler$zfn000$sendToDimension(PlayerList.java:1464) ~[?:?]
	at net.minecraft.server.management.PlayerList.func_232642_a_(PlayerList.java) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:843) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$17464/944649351.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[02Mar2021 11:56:24.361] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report

Note: This error was encountered while running 1.16.5 Forge 36.0.43, Immersive Portals 0.14 (Forge), and RFTools Dimensions 1.16-7.0.3.

Another instance:

> [02Mar2021 12:48:16.680] [Server thread/INFO] [Portal/]: ignored dubious move packet rftoolsdim:osmium 382.5854559629825 70.0 -134.61030866935235 8.5 66.5 8.5
[02Mar2021 12:48:16.680] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.RuntimeException: Missing Dimension ResourceKey[minecraft:dimension / rftoolsdim:osmium]
	at com.qouteall.immersive_portals.dimension_sync.DimensionIdRecord.getIntId(DimensionIdRecord.java:39) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.immersive_portals.dimension_sync.DimId.writeWorldId(DimId.java:24) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.hiding_in_the_bushes.network.StcDimensionConfirm.encode(StcDimensionConfirm.java:35) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.hiding_in_the_bushes.network.NetworkMain$$Lambda$14052/2025260581.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryEncode$4(IndexedMessageCodec.java:134) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$17660/84339078.accept(Unknown Source) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryEncode(IndexedMessageCodec.java:132) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.build(IndexedMessageCodec.java:147) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.encodeMessage(SimpleChannel.java:85) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.toBuffer(SimpleChannel.java:98) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.toVanillaPacket(SimpleChannel.java:129) ~[?:?]
	at com.qouteall.hiding_in_the_bushes.MyNetwork.createStcDimensionConfirm(MyNetwork.java:57) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.immersive_portals.teleportation.ServerTeleportationManager.sendPositionConfirmMessage(ServerTeleportationManager.java:342) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.immersive_portals.teleportation.ServerTeleportationManager.updateForPlayer(ServerTeleportationManager.java:391) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.immersive_portals.teleportation.ServerTeleportationManager.tick(ServerTeleportationManager.java:357) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.immersive_portals.teleportation.ServerTeleportationManager$$Lambda$14078/1023447740.accept(Unknown Source) ~[?:?]
	at com.qouteall.immersive_portals.my_util.Signal.lambda$connectWithWeakRef$1(Signal.java:35) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.immersive_portals.my_util.Signal$$Lambda$14079/2138876774.run(Unknown Source) ~[?:?]
	at com.qouteall.immersive_portals.my_util.Signal.lambda$emit$0(Signal.java:18) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.immersive_portals.my_util.Signal$$Lambda$17429/1778875325.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51]
	at com.qouteall.immersive_portals.my_util.Signal.emit(Signal.java:18) ~[?:0.16-mc1.16.5-forge]
	at net.minecraft.server.MinecraftServer.handler$zfm000$onServerTick(MinecraftServer.java:2747) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:879) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$17481/1941676342.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[02Mar2021 12:48:16.690] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report

Note: This error was encountered while running 1.16.5 Forge 36.0.43, Immersive Portals 0.16 (Forge), and RFTools Dimensions 1.16-7.0.4

A [similar post](https://github.com/McJtyMods/RFToolsDimensions/issues/310) for this error was made on the RFTools Dimensions GitHub, and the creator there suggested it was a conflict between their mod and Immersive Portals, along with suggesting it be reported here as well.

Edit: The same error occurs when running both these mods on a server, and in fact will crash the server along with the user client who enters the dimension for the first time.

**Comment by F0x06** [comment]
Same error

**Comment by hodo1962** [comment]
I have the same problem with the newest version of Rftools Dimension. The only way to avoid crash ist to log of and on after building the new dimension, but this will corrupt the new dimension.
