### ISSUE TITLE
NullPointerException upon loading a world

### ISSUE THREAD

**Issue by DestinyPlayer** [qouteall/ImmersivePortalsModForForge#247]
Whenever I try to create a new world, or load an existing world, Immersive Portals for Forge ends up perma-looping the game with this error _(included for ease of searching in the log)_:
(Lnet/minecraftforge/event/world/WorldEvent$Load;)V java.lang.NullPointerException

Full log - https://www.dropbox.com/s/2qspbnzsz6iow68/latest.log?dl=0
Crash log - doesn't generate, the game just gets stuck in a permanent loop of getting the same errors over and over again.

Minecraft - 1.16.5
Forge - 36.1.1
Immersive Portals - 0.16-mc1.16.5-forge
Java - 1.60._291 64bit
Java arguments - None
OS - Windows 7

Complete Modpack - https://prnt.sc/12bt4xn _(FerriteCore and OptiFine have been switched off for this log, the crash still happens)_

**Comment by qouteall** [comment]
```
java.lang.NullPointerException
	at com.qouteall.imm_ptl_peripheral.alternate_dimension.AlternateDimensions.isAlternateDimension(AlternateDimensions.java:156)
	at net.minecraft.client.world.ClientWorld$ClientWorldInfo.handler$zjm000$onGetSkyDarknessHeight(ClientWorld.java:979)
	at net.minecraft.client.world.ClientWorld$ClientWorldInfo.func_239159_f_(ClientWorld.java)
	at lumien.chunkanimator.handler.WorldEventHandler.worldLoad(WorldEventHandler.java:20)
```
related with chunkanimator

**Comment by DestinyPlayer** [comment]
Huh, that is indeed an issue. I guess I'll cross post this to the Chunk Animator issue tracker as well, since this seems to ONLY happen when Immersive Portals and Chunk Animator are both in the pack, even if only so that the devs are aware of this issue.

EDIT: already a thing apparently.

**Comment by DestinyPlayer** [comment]
As of the latest version of Chunk Animator (1.2.4), the incompatibility has, supposedly, been fixed.
