### ISSUE TITLE
Cant work with MohistMC server， and after removing this，sth is wrong with the portals

### ISSUE THREAD

**Issue by Daman-Yang** [qouteall/ImmersivePortalsModForForge#288]
1.After I put this mod in my MohistMC server（it supports forge mods and plugins），when i die，i will be disconnected automatically and the server throws an exception.
2.After i removed this mod off the “mods” folder，all of the portals including the nether portals cant be activated.

**Comment by qouteall** [comment]
Does this issue occur with only immersive portals mod? If so maybe newer versions of forge have conflicts with this mod.

**Comment by Dakewlmancoding** [comment]
Having the exact same issue, so I'll weigh in:
When I die and press respawn, it kicks me from the game. 

The clientside (shown) error is: 
`Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Missing Dimension null`

The serverside error is: 
`[00:11:00 WARN]:  java.lang.RuntimeException: Missing Dimension null
[00:11:00 WARN]: 	at com.qouteall.immersive_portals.dimension_sync.DimensionIdRecord.getIntId(DimensionIdRecord.java:39)
[00:11:00 WARN]: 	at com.qouteall.immersive_portals.dimension_sync.DimId.writeWorldId(DimId.java:24)
[00:11:00 WARN]: 	at net.minecraft.network.play.server.SPlayerPositionLookPacket.handler$zii000$onWrite(SourceFile:530)
[00:11:00 WARN]: 	at net.minecraft.network.play.server.SPlayerPositionLookPacket.func_148840_b(SourceFile:52)
[00:11:00 WARN]: 	at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:41)
[00:11:00 WARN]: 	at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:15)
[00:11:00 WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[00:11:00 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[00:11:00 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[00:11:00 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[00:11:00 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[00:11:00 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[00:11:00 WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[00:11:00 WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[00:11:00 WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$5(NetworkManager.java:212)
[00:11:00 WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[00:11:00 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[00:11:00 WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[00:11:00 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[00:11:00 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)`

Connection times out when attempting to rejoin. Restarting the server solves this.

I am using a MohistMC server on Ubuntu 20.x (which I think means Forge 36.2.4? But I'm certain that it's Forge 36.2.x)

Good luck and happy bug hunting!

**Comment by Gazer10** [comment]
> 2.After i removed this mod off the “mods” folder，all of the portals including the nether portals cant be activated.

Had the same issue, the reason is because the immersive portals "portal block" is still inside the frame. What you need to do is redownload the mod, go into creative mod, and you will see outlines inside the portal frame (as if there is an invisible block). Destroy them all, delete the mod again, and done. (DONT reactivate the portals before you delete the mod).

**Comment by Dakewlmancoding** [comment]
Can confirm Gazer10's response solves the issue when removing the mod. You can also fill in the portals with another block and relight it, after removing the mod.

This does, however, still leave the primary issue unaddressed.
