### ISSUE TITLE
Game crashes when trying to load with optifine

### ISSUE THREAD

**Issue by Duhitsben** [qouteall/ImmersivePortalsModForForge#42]
When I  launch the game with immersive portal and optifine it crashes. Here's the crash report

---- Minecraft Crash Report ----
// Why did you do that?

Time: 29/02/20 7:50 AM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.client.renderer.entity.EntityRendererManager.validateRendererExistence()V
	at net.minecraftforge.fml.client.registry.RenderingRegistry.loadEntityRenderers(RenderingRegistry.java:50) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.postSidedRunnable(ClientModLoader.java:127) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2794/2002170878.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$loadMods$14(ModLoader.java:158) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$2975/231567597.run(Unknown Source) ~[?:?] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
	at net.minecraft.resources.AsyncReloader$$Lambda$2872/236972673.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:173) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:898) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.1.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$406/452015229.call(Unknown Source) [forge-1.15.2-31.1.1.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2781049768 bytes (2652 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre9.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.1.1.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.1
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.1-client.jar Minecraft {minecraft@1.15.2 ENQUEUE_IMC}
		FPS-Reducer-Mod-1.15.2.jar FPS Reducer {fpsreducer@mc1.15.2-1.14.1 ENQUEUE_IMC}
		Useful-Backpacks-Mod-1.15.2.jar Useful Backpacks {usefulbackpacks@1.9.0.52 ENQUEUE_IMC}
		Colorful-Armor-Mod-1.15.2.jar Colorful Armor {colorfularmor@1.0 ENQUEUE_IMC}
		forge-1.15.2-31.1.1-universal.jar Forge {forge@31.1.1 ENQUEUE_IMC}
		U-Team-Core-1.15.2.jar U Team Core {uteamcore@2.10.0.146 ENQUEUE_IMC}
		FastLeafDecay-Mod-1.15.2.jar FastLeafDecay {fastleafdecay@v20 ENQUEUE_IMC}
		damage_indicator-0.0.9.jar Ama's Damage Indicator {damage_indicator@0.0.9 ENQUEUE_IMC}
		Xaeros-Minimap-Mod-1.15.2.jar Xaero's Minimap {xaerominimap@20.1.0 ENQUEUE_IMC}
		Hwyla-Mod-1.15.2.jar Waila {waila@version ENQUEUE_IMC}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 ENQUEUE_IMC}
	Launched Version: 1.15.2-forge-31.1.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 750/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.50, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Borderless+Glass.zip (incompatible), file/Clear Glass Pack 1.11 or 1.12.zip (incompatible)
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre9
	OptiFine Build: 20200223-095745
	Render Distance Chunks: 16
	Mipmaps: 3
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 442.50
	OpenGlRenderer: GeForce GTX 750/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by qouteall** [comment]
preview optifine is not compatible with forge now
