### ISSUE TITLE
Empty or none existent pool: minecraft:none

### ISSUE THREAD

**Issue by LoganDark** [qouteall/ImmersivePortalsModForForge#81]
```
23:45:16.485
[m[32m[23:45:16] [Render thread/INFO] [Portal/]: [Portal] Client Changed Dimension from immersive_portals:alternate3 to immersive_portals:alternate4 time: 1360
23:45:17.256
[m[33m[23:45:17] [Server-Worker-26/WARN] [minecraft/JigsawManager]: Empty or none existent pool: minecraft:none
23:45:23.492
[m[33m[23:45:23] [Server-Worker-25/WARN] [minecraft/JigsawManager]: Empty or none existent pool: minecraft:none
23:45:23.492
[m[33m[23:45:23] [Server-Worker-25/WARN] [minecraft/JigsawManager]: Empty or none existent pool: minecraft:none
23:45:23.492
[m[33m[23:45:23] [Server-Worker-25/WARN] [minecraft/JigsawManager]: Empty or none existent pool: minecraft:none
23:45:25.969
[m[33m[23:45:25] [Server-Worker-28/WARN] [minecraft/JigsawManager]: Empty or none existent pool: minecraft:none
23:45:27.624
[m[33m[23:45:27] [Server-Worker-28/WARN] [minecraft/JigsawManager]: Empty or none existent pool: minecraft:none
23:45:29.503
[m[33m[23:45:29] [Server-Worker-24/WARN] [minecraft/JigsawManager]: Empty or none existent pool: minecraft:none
23:45:30.924
[m[33m[23:45:30] [Server-Worker-24/WARN] [minecraft/JigsawManager]: Empty or none existent pool: minecraft:none
23:45:36.849
[m[33m[23:45:36] [Server-Worker-24/WARN] [minecraft/JigsawManager]: Empty or none existent pool: minecraft:none
23:45:36.850
[m[33m[23:45:36] [Server-Worker-24/WARN] [minecraft/JigsawManager]: Empty or none existent pool: minecraft:none
23:45:38.143
[m[33m[23:45:38] [Server-Worker-24/WARN] [minecraft/JigsawManager]: Empty or none existent pool: minecraft:none
23:45:40.489
[m[33m[23:45:40] [Server-Worker-24/WARN] [minecraft/JigsawManager]: Empty or none existent pool: minecraft:none
23:45:40.489
[m[33m[23:45:40] [Server-Worker-24/WARN] [minecraft/JigsawManager]: Empty or none existent pool: minecraft:none
23:45:43.100
[m[33m[23:45:43] [Server-Worker-28/WARN] [minecraft/JigsawManager]: Empty or none existent pool: minecraft:none
23:45:45.614
[m[33m[23:45:45] [Server-Worker-28/WARN] [minecraft/JigsawManager]: Empty or none existent pool: minecraft:none
23:45:45.615
[m[33m[23:45:45] [Server-Worker-28/WARN] [minecraft/JigsawManager]: Empty or none existent pool: minecraft:none
```

I get `Empty or none existent pool: minecraft:none` once every second and the server freezes forever. No chat messages go through, no commands, nothing that requires server interaction.

Sigh. Another mod another conflict. I'll let you know if I find the culprit.

**Comment by LoganDark** [comment]
I feel like this is the same issue yet I removed BoP from the pack. So it's either another incompatibility, or you should try fixing the BoP issue and see if it solves this one too.

(The BoP one doesn't spam console with JigsawManager logs though)

Moving through a ceil portal from overworld->alternate3 works, but alternate3->alternate4 causes this.

Let me know if you want me to spend an hour or two searching my mods for the culprit again. :P

**Comment by MazeusXenon** [comment]
I am seeing the same JigsawManager errors when we try to place the initial camp from Mine Colonies mod. The screen log shows about 50 of these and then crashes the server so hard, it reset likes the World folder was empty!

We did have to move to 31.1.77 of Forge because of a different mod requiring it and that is when this started to happen.

**Comment by MazeusXenon** [comment]
Spoke to Mine Colonies and they said it looks like an Immersive Portals things clashing with their mod. Here is a log I do get from the server when it finally crashes (after the lines of error in the screen log):
`java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
	at sun.misc.Unsafe.park(Native Method) ~[?:1.8.0_252] {}
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215) ~[?:1.8.0_252] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_223705_bi(SourceFile:139) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:129) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_212849_a_(SourceFile:139) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinServerChunkManager,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinServerChunkProvider,pl:mixin:A}
	at net.minecraft.world.World.func_217353_a(World.java:149) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinWorld,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.IWorldReader.func_217348_a(IWorldReader.java:101) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_212866_a_(World.java:145) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinWorld,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_180495_p(World.java:361) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinWorld,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.ldtteam.structurize.util.InstantStructurePlacer.placeStructure(InstantStructurePlacer.java:174) ~[?:0.10.315-ALPHA] {re:classloading}
	at com.minecolonies.api.util.InstantStructurePlacer.placeStructure(InstantStructurePlacer.java:107) ~[?:0.11.939-ALPHA] {re:classloading}
	at com.ldtteam.structurize.util.ScanToolOperation.apply(ScanToolOperation.java:168) ~[?:0.10.315-ALPHA] {re:classloading}
	at com.ldtteam.structurize.management.Manager.onWorldTick(Manager.java:70) ~[?:0.10.315-ALPHA] {re:classloading}
	at com.ldtteam.structurize.event.EventSubscriber.onWorldTick(EventSubscriber.java:87) ~[?:0.10.315-ALPHA] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_409_EventSubscriber_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.1.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.1.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreWorldTick(BasicEventHooks.java:94) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252] {}
`
