### ISSUE TITLE
Error during the load_registries event phase

### ISSUE THREAD

**Issue by Parval** [qouteall/ImmersivePortalsModForForge#94]
I have all of my other mods disabled but the game still crashes on startup 

[08May2020 15:35:19.496] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Parvall, --version, MultiMC5, --gameDir, E:/google/mmc-stable-win32/MultiMC/instances/UR/.minecraft, --assetsDir, E:/google/mmc-stable-win32/MultiMC/assets, --assetIndex, 1.15, --uuid, 8bf8d8bf73334a459d6cc1f9d16b1f8b, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 31.1.10, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200122.131323, --width, 854, --height, 480]
[08May2020 15:35:19.501] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 5.0.0-milestone.4+67+b1a340b starting: java version 1.8.0_241 by Oracle Corporation
[08May2020 15:35:19.996] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[08May2020 15:35:20.759] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, MultiMC5, --gameDir, E:\google\mmc-stable-win32\MultiMC\instances\UR\.minecraft, --assetsDir, E:\google\mmc-stable-win32\MultiMC\assets, --uuid, 8bf8d8bf73334a459d6cc1f9d16b1f8b, --username, Parvall, --assetIndex, 1.15, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 854, --height, 480]
[08May2020 15:35:22.414] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: Parvall
[08May2020 15:35:27.286] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.2.2 build 10
[08May2020 15:35:28.689] [modloading-worker-2/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 31.1.10, for MC 1.15.2 with MCP 20200122.131323
[08May2020 15:35:28.689] [modloading-worker-2/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v31.1.10 Initialized
[08May2020 15:35:29.156] [Render thread/WARN] [net.minecraft.entity.EntityType/]: No data fixer registered for entity immersive_portals:portal
[08May2020 15:35:29.176] [Render thread/WARN] [net.minecraft.entity.EntityType/]: No data fixer registered for entity immersive_portals:nether_portal_new
[08May2020 15:35:29.180] [Render thread/WARN] [net.minecraft.entity.EntityType/]: No data fixer registered for entity immersive_portals:end_portal
[08May2020 15:35:29.182] [Render thread/WARN] [net.minecraft.entity.EntityType/]: No data fixer registered for entity immersive_portals:mirror
[08May2020 15:35:29.185] [Render thread/WARN] [net.minecraft.entity.EntityType/]: No data fixer registered for entity immersive_portals:breakable_mirror
[08May2020 15:35:29.187] [Render thread/WARN] [net.minecraft.entity.EntityType/]: No data fixer registered for entity immersive_portals:global_tracked_portal
[08May2020 15:35:29.192] [Render thread/WARN] [net.minecraft.entity.EntityType/]: No data fixer registered for entity immersive_portals:border_portal
[08May2020 15:35:29.208] [Render thread/WARN] [net.minecraft.entity.EntityType/]: No data fixer registered for entity immersive_portals:end_floor_portal
[08May2020 15:35:29.213] [Render thread/WARN] [net.minecraft.entity.EntityType/]: No data fixer registered for entity immersive_portals:loading_indicator
[08May2020 15:35:29.219] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: Mixin is NOT loaded. Install MixinBootstrap!!!
	Index: 3
	Listeners:
		0: NORMAL
		1: ASM: class com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents onItemRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		2: ASM: class com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents onEntityRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		3: ASM: class com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents onEffectRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		4: ASM: class com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents onPotionRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		5: ASM: class com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents onDimensionRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		6: ASM: class com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents onBlocksRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
java.lang.RuntimeException: Mixin is NOT loaded. Install MixinBootstrap!!!
	at com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents.onEffectRegistry(ModMainForge.java:494)
	at net.minecraftforge.eventbus.ASMEventHandler_10_RegistryEvents_onEffectRegistry_Register.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source)
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source)
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:125)
	at java.util.ArrayList.forEach(Unknown Source)
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:125)
	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96)
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71)
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:197)
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:189)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:964)
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:189)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113)
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

[08May2020 15:35:29.223] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event RegistryEvent.Register<minecraft:mob_effect> dispatch for modid immersive_portals
java.lang.RuntimeException: Mixin is NOT loaded. Install MixinBootstrap!!!
	at com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents.onEffectRegistry(ModMainForge.java:494) ~[?:0.17]
	at net.minecraftforge.eventbus.ASMEventHandler_10_RegistryEvents_onEffectRegistry_Register.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) ~[?:31.1]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_241]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:125) ~[?:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:125) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96) ~[?:?]
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71) ~[?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:197) ~[?:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:189) ~[?:?]
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:964) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:189) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) ~[?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:393) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:166) ~[minecraft-1.15.2-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.1.10-launcher.jar:31.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:39) [ForgeWrapper-1.4.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[08May2020 15:35:29.231] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event LOAD_REGISTRIES, 1 errors found
[08May2020 15:35:29.231] [Render thread/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) ~[eventbus-2.0.0-milestone.1-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) ~[?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:393) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:166) ~[minecraft-1.15.2-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.1.10-launcher.jar:31.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:39) [ForgeWrapper-1.4.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[08May2020 15:35:30.308] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[08May2020 15:35:30.353] [Render thread/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Default, Mod Resources
[08May2020 15:35:32.224] [Server-Worker-7/ERROR] [net.minecraftforge.fml.ModLoader/LOADING]: Skipping lifecycle event SETUP, 1 errors found.
[08May2020 15:35:32.225] [Server-Worker-7/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event SETUP, 1 errors found
[08May2020 15:35:32.225] [Server-Worker-7/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) ~[eventbus-2.0.0-milestone.1-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:123) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:105) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_241]
[08May2020 15:35:32.990] [Server-Worker-4/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: Exception loading blockstate definition: immersive_portals:blockstates/portal_placeholder.json: java.io.FileNotFoundException: immersive_portals:blockstates/portal_placeholder.json
[08May2020 15:35:32.990] [Server-Worker-4/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: Exception loading blockstate definition: 'immersive_portals:blockstates/portal_placeholder.json' missing model for variant: 'immersive_portals:portal_placeholder#axis=x'
[08May2020 15:35:32.990] [Server-Worker-4/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: Exception loading blockstate definition: 'immersive_portals:blockstates/portal_placeholder.json' missing model for variant: 'immersive_portals:portal_placeholder#axis=y'
[08May2020 15:35:32.991] [Server-Worker-4/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: Exception loading blockstate definition: 'immersive_portals:blockstates/portal_placeholder.json' missing model for variant: 'immersive_portals:portal_placeholder#axis=z'
[08May2020 15:35:33.357] [Server-Worker-4/WARN] [net.minecraft.client.renderer.texture.AtlasTexture/]: Texture immersive_portals:block/portal_helper with size 319x318 limits mip level from 4 to 0
[08May2020 15:35:33.511] [Server-Worker-4/ERROR] [net.minecraftforge.fml.ModLoader/LOADING]: Skipping lifecycle event ENQUEUE_IMC, 1 errors found.
[08May2020 15:35:33.511] [Server-Worker-4/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event ENQUEUE_IMC, 1 errors found
[08May2020 15:35:33.511] [Server-Worker-4/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) ~[eventbus-2.0.0-milestone.1-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.finishModLoading(ClientModLoader.java:137) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$4(ClientModLoader.java:107) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniRun(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_241]
[08May2020 15:35:33.633] [Render thread/INFO] [net.minecraft.client.audio.SoundSystem/]: OpenAL initialized.
[08May2020 15:35:33.634] [Render thread/INFO] [net.minecraft.client.audio.SoundEngine/SOUNDS]: Sound engine started
[08May2020 15:35:33.778] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[08May2020 15:35:33.958] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128x4 minecraft:textures/atlas/signs.png-atlas
[08May2020 15:35:33.960] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[08May2020 15:35:33.966] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[08May2020 15:35:33.973] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[08May2020 15:35:33.975] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[08May2020 15:35:33.978] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[08May2020 15:35:34.293] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[08May2020 15:35:34.297] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[08May2020 15:35:34.299] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas

**Comment by Parval** [comment]
Turns out I was missing MixinBootstrap
