### ISSUE TITLE
Immersive portals is incompatible with minecolonies

### ISSUE THREAD

**Issue by maximus1218** [qouteall/ImmersivePortalsModForForge#99]
While using this mod with minecolonies, no buildings can be placed. This makes minecolonies obsolete.

**Comment by maximus1218** [comment]
Thank you.

**Comment by LoganDark** [comment]
Coremods in and of themselves are not bad things and aren't always the reason for things screwing up. However I think forge compatibility could be improved at the moment so I'm leaving this open.

You should note that Forge support has always been kind of experimental and right now Fabric has the most stable version of IP. Unfortunately there's not much I can do about this but @qouteall might be able to help you out.

**Comment by maximus1218** [comment]
Alright, well thank you for your help. Are the mods compatible at the moment using Fabric?

**Comment by LoganDark** [comment]
I'm not sure if minecolonies supports Fabric at all. However, Immersive Portals is compatible with most Fabric mods excluding Sodium.

**Comment by maximus1218** [comment]
thank you.

**Comment by LoganDark** [comment]
Since all Fabric mods are technically "coremods" and even encouraged to use Mixin, they are usually compatible with each other when they don't have conflicting mixins. However, on Forge, coremods are heavily frowned upon and nobody wants to deal with them or be compatible with them - hence the issue with minecolonies being weird, since Immersive Portals skirts around the Forge API a little.

**Comment by maximus1218** [comment]
So should the step to fix this be on the part of minecolonies, in fixing compatibility issues with IP?

**Comment by qouteall** [comment]
Is anything abnormal shown in the log when you try to put the building?

**Comment by LoganDark** [comment]
I have a feeling it's a little bit of both. On one paw, Immersive Portals does modify vanilla a LOT. Multiple worlds, chunkloading patches, the works. On the other, most Forge mods exclusively use the Forge API and do not ever expect modifications to the base game. This opens up the door for conflicts when Minecolonies expects vanilla to be unmodified. Since the Forge API is the only API you are encouraged to use, and the community turns against you if you look outside of that, people are taught not to expect things and that all coremods are bad.

IP does things outside the Forge api that Forge mods don't expect, so things may break. Fixing these incompatibilites can be done on our side _or_ their side. IP already has some edge cases for other mods.

**Comment by maximus1218** [comment]
I'm not great at spotting abnormalities in error log, but here it is...

java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05) at sun.misc.Unsafe.park(Native Method) ~[?:1.8.0_252] {} at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215) ~[?:1.8.0_252] {} at net.minecraft.util.concurrent.ThreadTaskExecutor.func_223705_bi(SourceFile:139) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:129) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} at net.minecraft.world.server.ServerChunkProvider.func_212849_a_(SourceFile:139) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinServerChunkManager,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinServerChunkProvider,pl:mixin:A} at net.minecraft.world.World.func_217353_a(World.java:149) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinWorld,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.world.IWorldReader.func_217348_a(IWorldReader.java:101) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A} at net.minecraft.world.World.func_212866_a_(World.java:145) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinWorld,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.world.World.func_180495_p(World.java:361) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinWorld,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A} at com.ldtteam.structurize.util.InstantStructurePlacer.placeStructure(InstantStructurePlacer.java:174) ~[?:0.10.315-ALPHA] {re:classloading} at com.minecolonies.api.util.InstantStructurePlacer.placeStructure(InstantStructurePlacer.java:107) ~[?:0.11.939-ALPHA] {re:classloading} at com.ldtteam.structurize.util.ScanToolOperation.apply(ScanToolOperation.java:168) ~[?:0.10.315-ALPHA] {re:classloading} at com.ldtteam.structurize.management.Manager.onWorldTick(Manager.java:70) ~[?:0.10.315-ALPHA] {re:classloading} at com.ldtteam.structurize.event.EventSubscriber.onWorldTick(EventSubscriber.java:87) ~[?:0.10.315-ALPHA] {re:classloading} at net.minecraftforge.eventbus.ASMEventHandler_409_EventSubscriber_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {} at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.1.0-service.jar:?] {} at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.1.0-service.jar:?] {} at net.minecraftforge.fml.hooks.BasicEventHooks.onPreWorldTick(BasicEventHooks.java:94) ~[?:?] {re:classloading} at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330) ~[?:?] {re:classloading,pl:accesstransformer:B} at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A} at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252] {}

**Comment by LoganDark** [comment]
@maximus1218 Would you mind uploading your log file straight to GitHub? That stack trace is just a blob of text, it's impossible to read the call stack properly.

**Comment by maximus1218** [comment]
oh yeah, sorry my bad, one moment,,,

**Comment by qouteall** [comment]
Firstly it lags probably because generating terrain in server main thread. Normally the server main thread should not be lagged by generating terrain. So maybe minecolonies is trying to place structure in a remote place in ticking thread and generating terrain lags the server.
Seems that you also installed Lithium. Try to uninstall IP and Lithium and see does this issue still happen.

**Comment by maximus1218** [comment]
I am not using my person computer at the moment, but the same log was posted [here](https://github.com/ldtteam/minecolonies/issues/4972), yesterday.

**Comment by MazeusXenon** [comment]
This is the log file from the post I made with Minecolonies. It should be the same file I copied the error from and into the link sent by maximum1218

[crash-2020-05-11_13.24.38-server.txt](https://github.com/qouteall/ImmersivePortalsModForForge/files/4624817/crash-2020-05-11_13.24.38-server.txt)

**Comment by lebanni** [comment]
I dont know if it's related and if this might help, but I had a crash aswell with minecolonies.

[crash-2020-05-26_19.59.19-client.txt](https://github.com/qouteall/ImmersivePortalsModForForge/files/4684133/crash-2020-05-26_19.59.19-client.txt)

[latest.log](https://github.com/qouteall/ImmersivePortalsModForForge/files/4684135/latest.log)
